URL_SERVICE = "https://cnt-60c911a5-e456-4a7a-803c-726cb04d5c5a.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
CREATE_USER_PATH = "/api/v1/users/"
KITS_PATH = "/api/v1/kits"